version: '3.3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=dbunit
      - POSTGRES_PASSWORD=dbunit
      - POSTGRES_DB=dbunit
    ports:
      - 5432:5432
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=dbunit
      - MYSQL_USER=dbunit
      - MYSQL_PASSWORD=dbunit
      - MYSQL_ROOT_PASSWORD=dbunit
      - TZ="America/Chicago"
    ports:
      - 3306:3306
  mssql:
    image: dbunit/dbunit-it-sqlserver:2.0.0
    ports:
      - 1433:1433
  oracle11:
    image: dbunit/dbunit-it-oracle11g:1.0.1
    ports:
      - 1521:1521