-- CREATE USER
CREATE USER dbunit IDENTIFIED BY dbunit;
GRANT CREATE SESSION TO dbunit;
GRANT CREATE TABLE TO dbunit;
GRANT CREATE VIEW TO dbunit;

-- ALLOW US TO CREATE TABLES
ALTER USER dbunit QUOTA 200m on SYSTEM;